using UnityEngine;

namespace V57.GoldPath
{
    /// <summary>
    /// Tags a Visual prefab generated by <c>AssemblyRunner.BuildPlaceholders()</c> because provider art is missing.
    /// The assembly tools replace such prefabs (same path/GUID) once the real art arrives; reviewers count them.
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class V57Placeholder : MonoBehaviour
    {
        [SerializeField] private string _assetId = string.Empty;
        [SerializeField] private string _assetName = string.Empty;
        [SerializeField] private string _reason = string.Empty;

        public string AssetId => _assetId;

        public string AssetName => _assetName;

        public string Reason => _reason;

        /// <summary>Edit-mode setup used by the assembly tools.</summary>
        public void Configure(string assetId, string assetName, string reason)
        {
            _assetId = assetId ?? string.Empty;
            _assetName = assetName ?? string.Empty;
            _reason = reason ?? string.Empty;
        }
    }
}
