'use strict';
// Generated: ui, scenes, input_map (TDD registries merged with ADD V57 fields).
const fs = require('fs');
const path = require('path');
const { normalizeAcs, ownerIds } = require('./crossref');
const { norm, matchId } = require('./fuzzy');

const exists = (root, rel) => !!rel && fs.existsSync(path.join(root, rel));

/** Collect ADD ids unknown to the TDD; reported (aggregated) by run.js via reportAddUnknown. */
function unknownAddRef(ctx, id, what) {
  if (!ctx.addUnknown) ctx.addUnknown = new Map();
  if (!ctx.addUnknown.has(what)) ctx.addUnknown.set(what, new Set());
  ctx.addUnknown.get(what).add(id);
}

function reportAddUnknown(ctx, mismatch) {
  const { issues, add } = ctx;
  for (const [what, set] of ctx.addUnknown || []) {
    const ids = [...set].sort();
    if (mismatch) {
      issues.add({ code: 'ADD_UNKNOWN_ID', level: 'conflict', area: 'add', where: add.file,
        message: `${ids.length} ADD ${what} value(s) not defined in the TDD: ${ids.join(', ')}`, fix: 'TDD authority: not merged into generated data', refs: [what] });
    } else {
      ids.forEach((id) => issues.add({ code: 'ADD_UNKNOWN_ID', level: 'conflict', area: 'add', where: add.file,
        message: `ADD ${what} "${id}" is not defined in the TDD`, fix: 'TDD authority: not merged into generated data', refs: [id] }));
    }
  }
}

function mergeSystems(list, ctx, what) {
  const out = [];
  for (const id of list) {
    if (id === 'standalone') { out.push(id); continue; }
    const r = ctx.resolve(id, ctx.c.systems, { what, where: ctx.add.file, area: 'add' });
    if (r.status === 'unknown') unknownAddRef(ctx, id, what);
    else out.push(r.match);
  }
  return out;
}

function buildUi(ctx) {
  const { tdd, add, c, issues, resolve, inv } = ctx;
  const byId = new Map();
  tdd.screens.forEach((s) => byId.set(s.id, { id: s.id, purpose: s.purpose, states: s.states, consumed_by: s.consumed_by,
    presentation: null, sprites: null, asset_id: null, text_keys: [], source: 'tdd' }));
  tdd.mechanics.forEach((m) => m.uiRefs.filter((u) => matchId(u, c.screens).status === 'unknown' && !byId.has(u)).forEach((u) => byId.set(u, {
    id: u, purpose: `placeholder (referenced by ${m.name}, missing from §9.1)`, states: [], consumed_by: [m.name],
    presentation: null, sprites: null, asset_id: null, text_keys: [], source: 'placeholder' })));
  for (const a of add.ui_screens) {
    const r = resolve(a.id, c.screens, { what: 'ui_screens id', where: `${add.file}:${a._line}`, area: 'add' });
    let target = r.status !== 'unknown' ? byId.get(r.match) : null;
    mergeSystems(a.consumed_by, ctx, 'ui_screens consumed_by');
    if (!target) {
      if (!a.consumed_by.includes('standalone')) { unknownAddRef(ctx, a.id, 'ui_screens id'); continue; }
      target = { id: a.id, purpose: a.purpose, states: a.states, consumed_by: ['standalone'], presentation: null, sprites: null, asset_id: null, text_keys: [], source: 'add' };
      byId.set(a.id, target);
    }
    target.presentation = a.presentation ? (/world|diegetic/i.test(a.presentation) ? 'world' : 'screen') : target.presentation;
    target.sprites = a.sprites || target.sprites;
    target.asset_id = a.asset_id || target.asset_id;
    target.text_keys = a.text_keys.length ? a.text_keys : target.text_keys;
  }
  const spriteDirs = new Set(inv.art.filter((f) => f.type === 'sprite' && f.prefix === 'SPR_').map((f) => f.asset));
  const noSprites = [];
  for (const s of byId.values()) {
    if (!s.sprites) s.sprites = spriteDirs.has(s.id) ? `Assets/_Game/Art/UI/Sprites/${s.id}` : null;
    if (s.sprites && !exists(inv.root, s.sprites)) {
      issues.add({ code: 'UI_SPRITES_MISSING', level: 'missing', area: 'cross', where: s.sprites, message: `sprites folder for ${s.id} does not exist`,
        fix: 'placeholder sprites generated by V57 assembly', refs: [s.id] });
    }
    if (!s.sprites) noSprites.push(s.id);
    s.presentation = s.presentation || null;
  }
  if (noSprites.length) {
    issues.add({ code: 'UI_NO_SPRITES', level: 'missing', area: 'cross', where: 'Assets/_Game/Art/UI/Sprites/',
      message: `${noSprites.length} screen(s) have no sprite folder (e.g. ${noSprites.slice(0, 4).join(', ')})`,
      fix: 'placeholder UI (flat panels + text) generated by V57 assembly', refs: noSprites });
  }
  const layouts = add.screen_layouts.map((l) => ({ id: l.id, mockup: l.mockup || null, contains: l.contains }));
  const mockups = new Set(inv.docs.filter((d) => d.startsWith('Docs/ArtDirection/UIMockups/')).map((d) => path.basename(d).replace(/\.[^.]+$/, '')));
  const needMockup = layouts.length ? layouts.map((l) => l.id) : [...byId.values()].filter((s) => s.presentation !== 'world').map((s) => s.id);
  const lacking = needMockup.filter((id) => {
    const l = layouts.find((x) => x.id === id);
    return l && l.mockup ? !exists(inv.root, l.mockup) && !mockups.has(id) : !mockups.has(id);
  });
  if (!add.found.screen_layouts) {
    issues.add({ code: 'ADD_SECTION_MISSING', level: 'missing', area: 'add', where: add.file || 'ADD', message: 'ADD has no ## screen_layouts section',
      fix: 'one layout per screen assumed; assembly stacks elements by §9.1 order', refs: ['screen_layouts'] });
  }
  if (lacking.length) {
    issues.add({ code: 'UI_MOCKUP_MISSING', level: 'missing', area: 'cross', where: 'Docs/ArtDirection/UIMockups/',
      message: `${lacking.length}/${needMockup.length} screen(s)/layout(s) without mockup (e.g. ${lacking.slice(0, 4).join(', ')})`,
      fix: 'M2 UI built from §9.1 + palette; reviewer scores UI without mockup reference', refs: lacking });
  }
  return { screens: [...byId.values()].map(({ source, ...s }) => ({ ...s, source })), layouts };
}

function levelOf(sceneId) {
  const m = String(sceneId).match(/^SCN_([A-Za-z0-9]+)/);
  return m ? m[1] : null;
}

function buildScenes(ctx) {
  const { tdd, add, c, issues, resolve, inv } = ctx;
  const scenes = tdd.scenes.map((s) => ({
    id: s.id, purpose: s.purpose, world_owner: ownerIds(s.world_owner).join(' + ') || s.world_owner || null,
    systems: s.systems, acs: normalizeAcs(s.acs, c, { where: `${tdd.file}:${s.line}`, area: 'tdd', owner: `§13.2 ${s.id}` }, issues, resolve),
    slice: false, blockout: null, markers: [], camera_ref: null,
  }));
  for (const a of add.scenes) {
    const r = resolve(a.id, c.scenes, { what: 'scene_manifest id', where: `${add.file}:${a._line}`, area: 'add' });
    const t = r.status !== 'unknown' ? scenes.find((s) => s.id === r.match) : null;
    mergeSystems(a.systems, ctx, 'scene_manifest systems');
    if (!t) { unknownAddRef(ctx, a.id, 'scene_manifest id'); continue; }
    t.slice = a.slice;
    t.blockout = a.blockout || null;
    t.markers = a.markers;
    t.camera_ref = a.camera_ref || null;
    normalizeAcs(a.acs, c, { where: `${add.file}:${a._line}`, area: 'add', owner: `ADD scene ${a.id}` }, issues, resolve)
      .forEach((x) => { if (!t.acs.includes(x)) t.acs.push(x); });
  }
  if (!scenes.some((s) => s.slice)) {
    const pick = scenes.find((s) => /^gameplay/i.test(s.purpose)) || scenes.find((s) => /vertical|slice/i.test(`${s.id} ${s.purpose}`))
      || scenes.find((s) => !/standalone|editor|preview/i.test(`${s.id} ${s.purpose} ${s.world_owner}`));
    if (pick) {
      pick.slice = true;
      issues.add({ code: 'SLICE_INFERRED', level: 'fixable', area: 'cross', where: `${tdd.file}:§13.2`,
        message: 'no scene_manifest entry with slice: true matches a TDD scene', fix: `slice scene inferred as ${pick.id} (first gameplay scene of §13.2)`, refs: [pick.id] });
    }
  }
  const blk = inv.art.filter((f) => f.type === 'blockout');
  for (const s of scenes) {
    if (!s.blockout) {
      const lvl = levelOf(s.id);
      const hit = lvl && blk.find((f) => norm(f.asset) === norm(lvl));
      s.blockout = hit ? hit.rel : null;
    }
    if (s.blockout && !exists(inv.root, s.blockout)) {
      // ADD may name the blockout by asset_id or asset_name (contract); resolve it to the BLK_ file on disk.
      const key = norm(s.blockout);
      const brief = add.briefs.find((b) => norm(b.asset_id) === key || norm(b.asset_name) === key);
      const mesh = brief && brief.files && brief.files.mesh ? String(brief.files.mesh).replace(/\\/g, '/') : null;
      const byName = blk.find((f) => norm(f.asset) === key || norm(f.rel.split('/').pop().replace(/^BLK_|\.fbx$/gi, '')) === key
        || (brief && norm(f.asset) === norm(brief.asset_name)));
      const resolved = mesh && exists(inv.root, mesh) ? mesh : byName ? byName.rel : null;
      if (resolved) s.blockout = resolved;
    }
    if (s.slice && (!s.blockout || !exists(inv.root, s.blockout))) {
      issues.add({ code: 'SLICE_NO_BLOCKOUT', level: 'missing', area: 'cross', where: s.blockout || `Assets/_Game/Art/Environment/Blockout/${levelOf(s.id) || s.id}/`,
        message: `slice scene ${s.id} has no BLK_ blockout on disk`, fix: 'greybox placeholder level generated (primitives from §11.5 / markers)', refs: [s.id] });
    }
    if (s.camera_ref && !exists(inv.root, s.camera_ref) && !exists(inv.root, `Docs/ArtDirection/Camera/${s.camera_ref}.png`)) {
      issues.add({ code: 'CAMERA_REF_MISSING', level: 'missing', area: 'cross', where: s.camera_ref, message: `camera_ref of ${s.id} not found`, fix: 'camera from §11.5 only', refs: [s.id] });
    }
  }
  return { scenes };
}

const KEYMAP = {
  space: '<Keyboard>/space', escape: '<Keyboard>/escape', esc: '<Keyboard>/escape', enter: '<Keyboard>/enter', slash: '<Keyboard>/slash',
  tab: '<Keyboard>/tab', 'left-click': '<Mouse>/leftButton', 'left click': '<Mouse>/leftButton', 'right-click': '<Mouse>/rightButton',
  'right trigger': '<Gamepad>/rightTrigger', 'left trigger': '<Gamepad>/leftTrigger', 'right shoulder': '<Gamepad>/rightShoulder',
  'left shoulder': '<Gamepad>/leftShoulder', start: '<Gamepad>/start', select: '<Gamepad>/select', 'left stick': '<Gamepad>/leftStick',
  'right stick': '<Gamepad>/rightStick', 'button south': '<Gamepad>/buttonSouth', 'a button': '<Gamepad>/buttonSouth',
};

function toPath(part) {
  if (/touch|tap|swipe/i.test(part)) return '<Touchscreen>/primaryTouch/press';
  const p = part.toLowerCase().replace(/^(hold|release|press|tap)\s*:?\s*/, '').replace(/\s+\d+(\.\d+)?\s*s$/, '').replace(/^hold\s+/, '').trim();
  if (KEYMAP[p]) return KEYMAP[p];
  if (/^[a-z0-9]$/.test(p)) return `<Keyboard>/${p}`;
  if (/^f\d{1,2}$/.test(p)) return `<Keyboard>/${p}`;
  return null;
}

function buildInput(ctx) {
  const { tdd, c } = ctx;
  const actions = tdd.inputs.map((a) => {
    const b = { keyboard: null, gamepad: null, touch: null, raw: a.binding };
    for (const part of a.binding.split(/\s*\/\s*/).filter((x) => !/^(\d|touch launch|hold|release)$/i.test(x))) {
      const p = toPath(part);
      if (!p) continue;
      const dev = p.startsWith('<Gamepad>') ? 'gamepad' : p.startsWith('<Touchscreen>') ? 'touch' : 'keyboard';
      if (!b[dev]) b[dev] = p;
    }
    const interaction = /^\s*hold/i.test(a.binding) ? 'hold' : /^\s*release/i.test(a.binding) ? 'release' : 'press';
    return { map: a.map || 'Gameplay', action: a.action, bindings: b, interaction, consumed_by: a.consumed_by };
  });
  tdd.mechanics.forEach((m) => m.playerInputs.filter((x) => matchId(x, c.actions).status === 'unknown').forEach((x) => {
    if (!actions.some((a) => a.action === x)) {
      actions.push({ map: 'Gameplay', action: x, bindings: { keyboard: null, gamepad: null, touch: null, raw: '' }, interaction: 'press', consumed_by: [m.name] });
    }
  }));
  return { actions };
}

module.exports = { buildUi, buildScenes, buildInput, levelOf, unknownAddRef, reportAddUnknown };
