'use strict';
// Writes Docs/Generated/<name>.yaml + json/<name>.json twins + localization.csv.
const fs = require('fs');
const path = require('path');
const YAML = require('yaml');

const GENERATED = ['package', 'asset_manifest', 'entities', 'mechanics', 'ui', 'scenes', 'input_map', 'camera', 'rendering', 'audio', 'tuning', 'acceptance', 'layouts'];

const HEADER = (name, version) => `# GENERATED by V57 intake ${version} — do not edit by hand.\n# Source of truth: provider TDD/ADD + assets on disk. Re-run: node V57/tools/intake/index.js --repo .\n# JSON twin: json/${name}.json\n`;

function csvCell(v) {
  const s = v === null || v === undefined ? '' : String(v);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

function writeFileIfChanged(file, content) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  try { if (fs.readFileSync(file, 'utf8') === content) return false; } catch (_) { /* new file */ }
  fs.writeFileSync(file, content);
  return true;
}

/**
 * @param {string} outDir absolute
 * @param {object} data {package:{...}, asset_manifest:{...}, ...}
 * @param {Array<{key,en}>} localization
 * @returns {string[]} written file paths (absolute)
 */
function writeGenerated(outDir, data, localization, version) {
  const written = [];
  for (const name of GENERATED) {
    const doc = data[name];
    if (!doc) continue;
    const y = path.join(outDir, `${name}.yaml`);
    const j = path.join(outDir, 'json', `${name}.json`);
    writeFileIfChanged(y, HEADER(name, version) + YAML.stringify(doc, { lineWidth: 0, aliasDuplicateObjects: false }));
    writeFileIfChanged(j, `${JSON.stringify(doc, null, 2)}\n`);
    written.push(y, j);
  }
  const csv = ['key,en', ...localization.map((r) => `${csvCell(r.key)},${csvCell(r.en)}`)].join('\n') + '\n';
  const c = path.join(outDir, 'localization.csv');
  writeFileIfChanged(c, csv);
  written.push(c);
  return written;
}

module.exports = { writeGenerated, writeFileIfChanged, GENERATED };
